title: Whoopi cushion
hero_image: images/cover.png
subtitle: Make a whoopee cushion with a Raspberry Pi
description: Make a whoopee cushion powered by a Raspberry Pi to prank your pals
original_url: https://www.raspberrypi.org/learning/whoopi-cushion/
theme: turquoise
listed: true
ingredient: false
technologies: 'python'
interests: 'jokes/pranks, music/sound'
steps:
  - title: Introduction
  - title: What you will need
  - title: Making the whoopee cushion
  - title: Connect the whoopee cushion to the Pi
  - title: Test the sound
  - title: Write a program in Python
  - title: Setting it up
  - title: What next?
    duration: 60
