---
title: Whoopi cushion
hero_image: images/cover.png
subtitle: Make a whoopee cushion with a Raspberry Pi
description: Make a whoopee cushion powered by a Raspberry Pi to prank your pals
original_url: https://www.raspberrypi.org/learning/whoopi-cushion/
theme: turquoise
duration: 60
listed: true
ingredient: false
technologies: python, raspberry-pi, electronic-components
curriculum: 1, design-1, programming-1, phys-comp-1, manufacture-1, community-0
interests: humour
hardware: raspberry-pi, electronic-components
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Making the whoopee cushion
- title: Connect the whoopee cushion to the Pi
  completion:
  - engaged
- title: Test the sound
- title: Write a program in Python
  completion:
  - internal
- title: Setting it up
  completion:
  - external